apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-boot-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spring-boot-app
  template:
    metadata:
      labels:
        app: spring-boot-app
    spec:
      containers:
        - name: spring-boot-app
          image: us-central1-docker.pkg.dev/pristine-sum-411008/demo-repository/hello-world:LATEST
          ports:
            - containerPort: 8080